/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ShellResourcesRouteImport } from './routes/_shell.resources'
import { Route as ShellPartnersRouteImport } from './routes/_shell.partners'
import { Route as ShellMindRouteImport } from './routes/_shell.mind'
import { Route as ShellGoalsRouteImport } from './routes/_shell.goals'
import { Route as ShellFaithRouteImport } from './routes/_shell.faith'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellCommunityRouteImport } from './routes/_shell.community'
import { Route as ShellCoachRouteImport } from './routes/_shell.coach'
import { Route as ShellChallengesRouteImport } from './routes/_shell.challenges'
import { Route as ShellBodyRouteImport } from './routes/_shell.body'
import { Route as ShellAdminRouteImport } from './routes/_shell.admin'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellResourcesRoute = ShellResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPartnersRoute = ShellPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMindRoute = ShellMindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGoalsRoute = ShellGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFaithRoute = ShellFaithRouteImport.update({
  id: '/faith',
  path: '/faith',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCommunityRoute = ShellCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCoachRoute = ShellCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChallengesRoute = ShellChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBodyRoute = ShellBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/admin': typeof ShellAdminRoute
  '/body': typeof ShellBodyRoute
  '/challenges': typeof ShellChallengesRoute
  '/coach': typeof ShellCoachRoute
  '/community': typeof ShellCommunityRoute
  '/dashboard': typeof ShellDashboardRoute
  '/faith': typeof ShellFaithRoute
  '/goals': typeof ShellGoalsRoute
  '/mind': typeof ShellMindRoute
  '/partners': typeof ShellPartnersRoute
  '/resources': typeof ShellResourcesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/admin': typeof ShellAdminRoute
  '/body': typeof ShellBodyRoute
  '/challenges': typeof ShellChallengesRoute
  '/coach': typeof ShellCoachRoute
  '/community': typeof ShellCommunityRoute
  '/dashboard': typeof ShellDashboardRoute
  '/faith': typeof ShellFaithRoute
  '/goals': typeof ShellGoalsRoute
  '/mind': typeof ShellMindRoute
  '/partners': typeof ShellPartnersRoute
  '/resources': typeof ShellResourcesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/body': typeof ShellBodyRoute
  '/_shell/challenges': typeof ShellChallengesRoute
  '/_shell/coach': typeof ShellCoachRoute
  '/_shell/community': typeof ShellCommunityRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/faith': typeof ShellFaithRoute
  '/_shell/goals': typeof ShellGoalsRoute
  '/_shell/mind': typeof ShellMindRoute
  '/_shell/partners': typeof ShellPartnersRoute
  '/_shell/resources': typeof ShellResourcesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/register'
    | '/admin'
    | '/body'
    | '/challenges'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/faith'
    | '/goals'
    | '/mind'
    | '/partners'
    | '/resources'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/register'
    | '/admin'
    | '/body'
    | '/challenges'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/faith'
    | '/goals'
    | '/mind'
    | '/partners'
    | '/resources'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/auth'
    | '/register'
    | '/_shell/admin'
    | '/_shell/body'
    | '/_shell/challenges'
    | '/_shell/coach'
    | '/_shell/community'
    | '/_shell/dashboard'
    | '/_shell/faith'
    | '/_shell/goals'
    | '/_shell/mind'
    | '/_shell/partners'
    | '/_shell/resources'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegisterRoute: typeof RegisterRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/resources': {
      id: '/_shell/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ShellResourcesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/partners': {
      id: '/_shell/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof ShellPartnersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mind': {
      id: '/_shell/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof ShellMindRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/goals': {
      id: '/_shell/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof ShellGoalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/faith': {
      id: '/_shell/faith'
      path: '/faith'
      fullPath: '/faith'
      preLoaderRoute: typeof ShellFaithRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/community': {
      id: '/_shell/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof ShellCommunityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/coach': {
      id: '/_shell/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof ShellCoachRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/challenges': {
      id: '/_shell/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ShellChallengesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/body': {
      id: '/_shell/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof ShellBodyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAdminRoute: typeof ShellAdminRoute
  ShellBodyRoute: typeof ShellBodyRoute
  ShellChallengesRoute: typeof ShellChallengesRoute
  ShellCoachRoute: typeof ShellCoachRoute
  ShellCommunityRoute: typeof ShellCommunityRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFaithRoute: typeof ShellFaithRoute
  ShellGoalsRoute: typeof ShellGoalsRoute
  ShellMindRoute: typeof ShellMindRoute
  ShellPartnersRoute: typeof ShellPartnersRoute
  ShellResourcesRoute: typeof ShellResourcesRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminRoute: ShellAdminRoute,
  ShellBodyRoute: ShellBodyRoute,
  ShellChallengesRoute: ShellChallengesRoute,
  ShellCoachRoute: ShellCoachRoute,
  ShellCommunityRoute: ShellCommunityRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFaithRoute: ShellFaithRoute,
  ShellGoalsRoute: ShellGoalsRoute,
  ShellMindRoute: ShellMindRoute,
  ShellPartnersRoute: ShellPartnersRoute,
  ShellResourcesRoute: ShellResourcesRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
  RegisterRoute: RegisterRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
